### ISSUE TITLE
This app on F-droid?

### ISSUE THREAD

**Issue by aleff-github** [Skyost/OpenAuthenticator#10]
Hi, how come this app is still not on f-droid?

**Comment by Skyost** [comment]
Hey,

It's a choice of mine. The problem is that, Open Authenticator uses some services provided by Google (Firebase / Billing services / ...). A device with F-Droid may not have these utilities installed.

**Comment by aleff-github** [comment]
> Hey,
> 
> It's a choice of mine. The problem is that, Open Authenticator uses some services provided by Google (Firebase / Billing services / ...). A device with F-Droid may not have these utilities installed.

I didn't know how to use Google services, so I imagined it might be a good alternative :-/

But yes, you are right

**Comment by Skyost** [comment]
It's a good idea really ! But as long as we're depending on Google, we can't really put this app on F-Droid.
