### ISSUE TITLE
Backup upload/export and where are files stored?

### ISSUE THREAD

**Issue by logiczny** [Skyost/OpenAuthenticator#3]
**Describe the bug**
Hi, first of all, thanks for your work. Solution like this was needed!
Unfortunately, I'm not finding solution to download my backups nor to restore them. Also, in which location those backups are stored? Would you please add this location to `readme` file?

**To Reproduce**
1. Go to settings in the app (android)
2. Click on `Backup now`
3. add password to backup, press `ok`
4. Click `Manage backups`
5. you can see list of backups and some arrow icon, which I don't know what it's doing actually. After I click on this arrow, I put password, and notification from the bottom says 'Success', but what succeeded?
6. Also, where are those backup stored exactly on the phone's memory?

**Expected behavior**

**Screenshots**
![image](https://github.com/user-attachments/assets/db3f616c-5423-4575-8204-0aa258172cc5)

**Smartphone (please complete the following information):**
 - Device: Nothing Phone 2
 - OS: Nothing 2.5.6, Android 14

**Comment by Skyost** [comment]
> Unfortunately, I'm not finding solution to download my backups nor to restore them. Also, in which location those backups are stored?

That's a good question ! They are stored in the application directory (as defined [here](https://pub.dev/documentation/path_provider/latest/path_provider/getApplicationDocumentsDirectory.html)) : it's [`/data/data/app.openauthenticator`](https://android.stackexchange.com/a/47951/262019).

If you're using a file explorer app installed on the device, then I don't believe you'll be able to access the files stored for a different app in it's Application Documents directory. I'll add a "Share" button to be able to access them easily.

> After I click on this arrow, I put password, and notification from the bottom says 'Success', but what succeeded?

You have restored the backup with success ! 🙂
