### ISSUE TITLE
Type 'int' is not a subtype of the type 'Duration'

### ISSUE THREAD

**Issue by adantiago** [Skyost/OpenAuthenticator#4]
![image](https://github.com/user-attachments/assets/62cd7144-4a15-4536-acd4-22e8a64365da)

**Comment by Skyost** [comment]
Hey,

Can you please provide more detail ?

**Comment by adantiago** [comment]
There is not much to explain, I was using it normally, it worked in the morning and, at noon, it no longer showed me the tokens and the error was displayed. Now it only shows this message and does not let me export or view the data to recover the tokens.

**Comment by adantiago** [comment]
I've been using the Windows version downloaded from the Microsoft Store and the Android app from the Google Store. So it's version 1.0.6 and using online sync with my email.

If I can, throughout the day I download the code from git, try compiling it and launching it locally to see if I still have the same error.

If I detect what's happening I'll attach screenshots or whatever is needed to correct it.

**Comment by adantiago** [comment]
I want to tell you that the error was corrected.

Thank you.

**Comment by Skyost** [comment]
Great 🙂
